name: ci-testing 

on: 
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 
      
jobs:

  style-check:
      runs-on: ubuntu-latest 
      steps:
        - name: Checkout Repository 
          uses: actions/checkout@v4

        - name: Setup Python 
          uses: actions/setup-python@v5 
          with:
            python-version: "3.12"

        - name: Install requirements 
          run: | 
            python -m pip install --upgrade pip 
            pip install ruff 

        - name: Run the linter 
          run: ruff check 

        - name: Run the format checker  
          run: ruff format --check 

  pytest: 
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.10", "3.11", "3.12"]
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v4 

        - name: Setup Python ${{ matrix.python-version }}
          uses: actions/setup-python@v5 
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install the package and requirements 
          run: | 
            python -m pip install --upgrade pip 
            pip install .[dev]

        - name: Run the basic test suite without coverage 
          run: pytest tests/test_inputs_base.py tests/test_utils.py

  pytest-full:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
      packages: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5 
        with:
          python-version: "3.12"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run the test suite with coverage 
        run: |
          PYTEST_CMD='cd /opt/aiida-dlpoly && pip install . && pytest --cov=aiida_dlpoly --cov-report=xml:/opt/aiida-dlpoly/coverage.xml' 
          IMAGE_NAME=ghcr.io/stfc/aiida-dlpoly/testing:latest 
          docker run --rm -v $(pwd):/opt/aiida-dlpoly $IMAGE_NAME bash -c "$PYTEST_CMD"

      - name: Report coverage to Coveralls 
        uses: coverallsapp/github-action@v2 
        with: 
          file: coverage.xml 
          base-path: aiida_chemshell